### ISSUE TITLE
latest docker image fails to run

### ISSUE THREAD

**Issue by hudon** [prosody/prosody-docker#15]
```
$ docker run --rm prosody/prosody
general             error       The version of LuaExpat on your system does not support stanza size limits, which may leave servers on untrusted networks (e.g. the internet) vulnerable to denial-of-service attacks. You should upgrade to LuaExpat 1.3.0 or higher as soon as possible. See http://prosody.im/doc/depends#luaexpat for more information.
```

**Comment by lloydwatkin** [comment]
@mwild1 how do I install the latest version of luaexpat to solve this issue?

**Comment by mwild1** [comment]
@hudon Are you sure Prosody fails to run? This is not a fatal error. If it does fail to run, I think you should look for other explanations why.

LuaExpat 1.3 is not yet packaged. As long as you have compression disabled there is not much to worry about though.

**Comment by xuhdev** [comment]
This issue makes me wonder why the image is built on ubuntu. The dependenciessuch as lua-* are from universe repo, for which canonical offers no support, even security issues. Moving to Debian should solve the issue as Debian supports the packages.

**Comment by mc0e** [comment]
If it's non fatal, perhaps it should say 'warning' rather than 'error'?

**Comment by mwild1** [comment]
@mc0e that's because we have a policy of raising the priority of warnings at startup to errors.

The premise being that such things are generally issues with the environment that the admin would want to be aware of. They're also not noisy, as they only happen once per run.

I agree the situation isn't ideal, but LuaExpat 1.3 is gradually getting out there, so it will eventually become a non-issue.

I'm going to close this issue as the original reporter didn't reply, so I'll assume everything was working aside from this log message.

**Comment by mc0e** [comment]
Can I suggest that this remain open until it's actually dealt with.  Others are likely to come looking here (as I did tonight) and it's best that they see the open issue (and don't open another).

**Comment by mwild1** [comment]
Created issue #18
