### ISSUE TITLE
How to backup user data from the container?

### ISSUE THREAD

**Issue by mpas** [prosody/prosody-docker#17]
When starting the container the data is stored inside the container. I tried to store the data outside using a mount volume. This seems not to work. Is there a way to get the data outside the running container.

**Comment by postblue** [comment]
Addressing the same issue here. As is, I cannot use the container and keep the data safe for my users.

**Comment by djmaze** [comment]
Mounting `/var/lib/prosody` as a volume should work (e.g. `docker run -v $PWD/.prosody:/var/lib/prosody ...`).

**Comment by mwild1** [comment]
This isn't really a bug, so I was going to close it. But you said you had issues using a volume mount... what was the problem with that? How/where did you mount it and what happened?

**Comment by bobobo1618** [comment]
I'll chip in and say that I had issues with this because within the container, the Prosody process is run as UID/GID 102/105. Permissions on my filesystem weren't set up to allow random users to modify the data so Prosody had no permissions.

A common solution to this problem is to allow setting UID/GID through an environment on the container. Another is to specify a hard coded UID/GID that the user can add permissions for.

**Comment by mwild1** [comment]
@bobobo1618 Ah, thanks for the tip - I was wondering how to solve that issue. When searching for solutions I just kept seeing references to unfinished features in Docker.

**Comment by mwild1** [comment]
I'm going to close this because I think it will be solved by #39.
